import SideBar from '@/components/SideBar'
import '@/styles/globals.css'
// here to change the title of website.
export const metadata = {
  title: 'ChatGPT-CCRP',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className='bg-green-500 max-w-xs h-screen overflow-y-auto
          md:min-w-[20rem]'>
            <SideBar/>
          </div>
          
          <div className="bg-green-400 flex-1">{children}</div>
        </div>
      </body>
    </html>
  )
}
