import { SessionProvider } from "../components/SessionProvider";
import SideBar from "@/components/SideBar";
import { getServerSession } from "next-auth";
import "@/styles/globals.css";
import { authOptions } from "../pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
import ClientProvider from "@/components/ClientProvider";
// here to change the title of website.
export const metadata = {
  title: "ChatGPT-CCRP",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  //console.log(session); // to verify the provider return the session or not
  return (
    <html>
      <head />
      <body>
        <SessionProvider session={session}>
          {/* here should be session, but there occurs a problem related to google authentication */}
          {!session ? (
            <Login />
          ) : (
            <div className="flex">
              <div
                className="bg-green-500 max-w-xs h-screen overflow-y-auto
                md:min-w-[20rem]"
              >
                <SideBar />
              </div>
              {/* ClientProvider - Notifications */}
              <ClientProvider />
              <div className="bg-green-400 flex-1">{children}</div>
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
